'use client'
import { useState } from 'react';
import Footer from './(components)/(Footer)/Footer';
import Header from './(components)/Header/Header'
import './global.scss'


export const metadata = {
  title: 'Hulo Dev Next js',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  const [isLock, setIsLock] = useState(false);

  const lockHandler = (lock) => {
      setIsLock(lock);
  }

  return (
    <html lang="en" className='scroll-smooth' style={{scrollBehavior:'smooth'}}>
      <body className={isLock ? 'lock' : ''}>
        <Header lock={lockHandler} setIsLock={setIsLock}/>
          {children}
          
        <Footer copy={true} partners={true} btn={false}/>
      </body>
    </html>
  )
}
