import './global.scss'


export const metadata = {
  title: 'Hulo Dev Next js',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
